### ISSUE TITLE
Backpack can be put into itself

### ISSUE THREAD

**Issue by zapteryx** [frost-byte/BackpacksX#2]
I'm not sure if this is the intended behaviour, but when a backpack is open, you can take that backpack and put it in the backpack's inventory. You then have to craft another backpack to get it back, which is kinda redundant because it has an enderchest-like inventory so it'll just open up the same inventory anyway.

**Comment by frost-byte** [comment]
Thanks for bringing this to my attention; I hope to have a fix for this in place soon.

**Comment by frost-byte** [comment]
The latest build includes a fix for this issue.
